services:
  kafka:
    container_name: kafka-node
    image: apache/kafka:3.9.0
    ports:
      - "9092:9092" # Kafka broker
      # - "9093:9093" # Kafka broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://kafka-node:9092,CONTROLLER://localhost:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-node:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: kafka-node
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-node:9092
    depends_on:
      - kafka

  kcat:
    container_name: kcat
    image: confluentinc/cp-kcat
    entrypoint: ["/bin/bash"]
    tty: true
    depends_on:
      - kafka

  producer:
    container_name: producer
    build:
      context: ./producer
    depends_on:
      - kafka

  consumer:
    container_name: consumer
    build:
      context: ./consumer
    depends_on:
      - kafka

volumes:
  kafka-data:
