services:
  kafka:
    container_name: kafka-node
    image: apache/kafka:3.9.0
    ports:
      - "9092:9092" # Kafka broker
      - "9093:9093" # Kafka broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka-node:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-node:9092,CONTROLLER://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_NUM_PARTITIONS: 3

      # KAFKA_LOG_DIRS: /tmp/kraft-combined-logs
    volumes:
      - kafka-data:/tmp/kraft-combined-logs

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: true
      KAFKA_CLUSTERS_0_NAME: kafka-node
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka-node:9092
    depends_on:
      - kafka

  kcat:
    container_name: kcat
    image: confluentinc/cp-kcat
    entrypoint: ["/bin/bash"]
    tty: true
    depends_on:
      - kafka

  producer:
    container_name: producer
    build:
      context: ./producer
    depends_on:
      - kafka

  consumer:
    container_name: consumer
    build:
      context: ./consumer
    depends_on:
      - kafka

volumes:
  kafka-data:
